#!/usr/bin/env python3
"""Android/Linux delivery readiness contract for the Central Brain prototype."""

from __future__ import annotations

import copy
from typing import Any


DELIVERY_REQ_IDS = [
    "DEL-001",
    "DEL-002",
    "DEL-003",
    "DEL-004",
    "DEL-005",
    "XSC-001",
    "XSC-002",
    "XSC-003",
    "XSC-004",
    "XSC-005",
    "XSC-006",
    "FW-U-003",
    "HW-002",
    "NV-F-003",
    "NV-F-004",
    "NV-F-005",
    "NV-P-001",
    "NV-P-002",
    "NV-P-003",
    "NV-P-006",
    "KH-003",
    "KH-006",
    "KH-007",
]


DELIVERY_READINESS_ROWS: list[dict[str, Any]] = [
    {
        "target": "android-debug-console",
        "platform": "Android",
        "current_state": "debug-apk-binder-sample",
        "ready_for": [
            "emulator validation",
            "Binder contract review",
            "AI SDK/Agent and governance debug visibility",
        ],
        "artifacts": [
            "central-brain/android-console/AndroidManifest.xml",
            "central-brain/bindings/android/java/com/centralbrain/binding/CentralBrainGatewayClient.java",
            "central-brain/bindings/android/java/com/centralbrain/binding/CentralBrainGatewayBinderService.java",
        ],
        "validation": [
            "bash tools/build_central_brain_console.sh",
            "bash tools/check_central_brain_binding_artifacts.sh",
        ],
        "blocked_by": [
            "target AAOS image signing and priv-app policy",
            "SELinux domain and service manager registration decision",
        ],
        "req_ids": ["DEL-001", "DEL-003", "DEL-004", "XSC-001", "XSC-002", "XSC-003", "XSC-004", "XSC-005", "XSC-006", "NV-F-004", "NV-F-005", "NV-P-002"],
    },
    {
        "target": "android-system-service-integration-note",
        "platform": "Android",
        "current_state": "documented-constraints",
        "ready_for": ["platform owner review", "privileged service planning", "Binder identity policy mapping review"],
        "artifacts": ["docs/CENTRAL_BRAIN_ANDROID_SYSTEM_SERVICE_INTEGRATION.md"],
        "validation": ["bash tools/check_central_brain_android_system_service_docs.sh"],
        "blocked_by": [
            "target framework/service registration owner",
            "production shared Runtime & Governance backend owner",
        ],
        "req_ids": ["DEL-001", "DEL-003", "DEL-004", "XSC-005", "XSC-006", "NV-P-002", "NV-P-005"],
    },
    {
        "target": "linux-cli-semantic-gateway",
        "platform": "Linux",
        "current_state": "active-cli-sample",
        "ready_for": ["contract smoke testing", "cockpit-domain developer inspection", "REST prototype fallback"],
        "artifacts": ["central-brain/linux-cli/central_brain_cli.py"],
        "validation": ["bash tools/smoke_central_brain_semantic_gateway.sh"],
        "blocked_by": ["replacement of REST prototype by target daemon/service boundary"],
        "req_ids": ["DEL-002", "DEL-003", "DEL-004", "DEL-005", "XSC-001", "XSC-002", "XSC-003", "XSC-004", "XSC-005", "XSC-006", "NV-F-004", "NV-F-005"],
    },
    {
        "target": "linux-ipc-daemon-sample",
        "platform": "Linux",
        "current_state": "active-unix-socket-sample",
        "ready_for": ["same-SoC IPC integration sample", "shared governance socket precheck review"],
        "artifacts": [
            "central-brain/bindings/linux/ipc/central_brain_ipc_daemon.py",
            "central-brain/bindings/linux/ipc/central_brain_ipc_client.py",
            "central-brain/bindings/linux/ipc/central_brain_governance_client.py",
        ],
        "validation": ["bash tools/smoke_central_brain_linux_ipc.sh"],
        "blocked_by": [
            "target distro service identity and socket path decision",
            "production shared governance daemon replacement",
        ],
        "req_ids": ["DEL-002", "DEL-003", "DEL-004", "DEL-005", "XSC-004", "XSC-005", "XSC-006", "NV-F-004", "NV-F-005", "NV-P-002"],
    },
    {
        "target": "linux-grpc-rpc-sample",
        "platform": "Linux",
        "current_state": "grpc-json-active-sample",
        "ready_for": ["proto review", "RPC contract smoke testing", "transport replacement planning"],
        "artifacts": [
            "central-brain/bindings/linux/proto/central_brain_gateway.proto",
            "central-brain/bindings/linux/grpc/central_brain_grpc_server.py",
            "central-brain/bindings/linux/grpc/central_brain_grpc_client.py",
        ],
        "validation": ["bash tools/smoke_central_brain_linux_grpc.sh"],
        "blocked_by": [
            "grpcio or C++ gRPC runtime availability",
            "production credential source and identity mapping",
        ],
        "req_ids": ["DEL-002", "DEL-003", "DEL-004", "DEL-005", "XSC-004", "XSC-005", "XSC-006", "NV-F-004", "NV-F-005", "NV-P-003"],
    },
    {
        "target": "event-subscription-lifecycle-transport-readiness-decision-matrix-activation-checklist-callback-watch-shape-cursor-replay-storage-backpressure-qos-evidence-readiness-rollup-activation-evidence-intake-review-status-retention-checklist-and-decision-status-rollup-contract",
        "platform": "Android/Linux",
        "current_state": "contract-only-not-brokered-with-activation-evidence-retention-owner-decisions-blocked",
        "ready_for": [
            "Uni Info Bus Event subscription lifecycle review",
            "subscribe/cancel command shape review",
            "callback/watch transport readiness review",
            "broker/cursor/backpressure owner decision review",
            "broker activation prerequisite evidence checklist review",
            "Android callback and Linux watch API shape review",
            "cursor, replay, and backpressure contract review",
            "cursor/replay storage owner, retention, ack, and cleanup review",
            "overflow schema, per-caller throttling, replay rate, ack timeout, and Runtime & Governance QoS evidence review",
            "end-to-end readiness blocker rollup review",
            "activation evidence intake reference-shape review",
            "activation evidence review status and no-store/no-workflow review",
            "activation evidence retention, URI rule, delete/export, and owner decision checklist review",
            "activation evidence decision status rollup review",
            "Android Binder and Linux IPC/gRPC parity inspection before a real broker is selected",
        ],
        "artifacts": [
            "GET /uib/events/subscriptions",
            "POST /uib/events/subscriptions/request",
            "POST /uib/events/subscriptions/cancel",
            "GET /uib/events/subscriptions/transport-readiness",
            "GET /uib/events/subscriptions/decision-matrix",
            "GET /uib/events/subscriptions/activation-checklist",
            "GET /uib/events/subscriptions/callback-watch-shape",
            "GET /uib/events/subscriptions/cursor-replay-storage",
            "GET /uib/events/subscriptions/backpressure-qos-evidence",
            "GET /uib/events/subscriptions/readiness-rollup",
            "POST /uib/events/subscriptions/activation-evidence",
            "GET /uib/events/subscriptions/activation-evidence/status",
            "GET /uib/events/subscriptions/activation-evidence/retention-checklist",
            "GET /uib/events/subscriptions/activation-evidence/decision-status-rollup",
            "Android Binder getEventSubscriptionsJson",
            "Android Binder requestEventSubscriptionJson",
            "Android Binder cancelEventSubscriptionJson",
            "Android Binder getEventSubscriptionTransportReadinessJson",
            "Android Binder getEventSubscriptionDecisionMatrixJson",
            "Android Binder getEventSubscriptionActivationChecklistJson",
            "Android Binder getEventSubscriptionCallbackWatchShapeJson",
            "Android Binder getEventSubscriptionCursorReplayStorageJson",
            "Android Binder getEventSubscriptionBackpressureQosEvidenceJson",
            "Android Binder getEventSubscriptionReadinessRollupJson",
            "Android Binder submitEventSubscriptionActivationEvidenceJson",
            "Android Binder getEventSubscriptionActivationEvidenceStatusJson",
            "Android Binder getEventSubscriptionActivationEvidenceRetentionChecklistJson",
            "Android Binder getEventSubscriptionActivationEvidenceDecisionStatusRollupJson",
            "Linux CLI event-subscriptions",
            "Linux CLI event-subscribe-request",
            "Linux CLI event-subscribe-cancel",
            "Linux CLI event-subscription-transport-readiness",
            "Linux CLI event-subscription-decision-matrix",
            "Linux CLI event-subscription-activation-checklist",
            "Linux CLI event-subscription-callback-watch-shape",
            "Linux CLI event-subscription-cursor-replay-storage",
            "Linux CLI event-subscription-backpressure-qos-evidence",
            "Linux CLI event-subscription-readiness-rollup",
            "Linux CLI event-subscription-activation-evidence",
            "Linux CLI event-subscription-activation-evidence-status",
            "Linux CLI event-subscription-activation-evidence-retention-checklist",
            "Linux CLI event-subscription-activation-evidence-decision-status-rollup",
            "Linux IPC uib.events.subscriptions.get",
            "Linux IPC uib.events.subscriptions.request",
            "Linux IPC uib.events.subscriptions.cancel",
            "Linux IPC uib.events.subscriptions.transport.readiness",
            "Linux IPC uib.events.subscriptions.decision.matrix",
            "Linux IPC uib.events.subscriptions.activation.checklist",
            "Linux IPC uib.events.subscriptions.callback.watch.shape",
            "Linux IPC uib.events.subscriptions.cursor.replay.storage",
            "Linux IPC uib.events.subscriptions.backpressure.qos.evidence",
            "Linux IPC uib.events.subscriptions.readiness.rollup",
            "Linux IPC uib.events.subscriptions.activation.evidence",
            "Linux IPC uib.events.subscriptions.activation.evidence.status",
            "Linux IPC uib.events.subscriptions.activation.evidence.retention.checklist",
            "Linux IPC uib.events.subscriptions.activation.evidence.decision.status.rollup",
            "Linux gRPC/RPC GetEventSubscriptions",
            "Linux gRPC/RPC RequestEventSubscription",
            "Linux gRPC/RPC CancelEventSubscription",
            "Linux gRPC/RPC GetEventSubscriptionTransportReadiness",
            "Linux gRPC/RPC GetEventSubscriptionDecisionMatrix",
            "Linux gRPC/RPC GetEventSubscriptionActivationChecklist",
            "Linux gRPC/RPC GetEventSubscriptionCallbackWatchShape",
            "Linux gRPC/RPC GetEventSubscriptionCursorReplayStorage",
            "Linux gRPC/RPC GetEventSubscriptionBackpressureQosEvidence",
            "Linux gRPC/RPC GetEventSubscriptionReadinessRollup",
            "Linux gRPC/RPC SubmitEventSubscriptionActivationEvidence",
            "Linux gRPC/RPC GetEventSubscriptionActivationEvidenceStatus",
            "Linux gRPC/RPC GetEventSubscriptionActivationEvidenceRetentionChecklist",
            "Linux gRPC/RPC GetEventSubscriptionActivationEvidenceDecisionStatusRollup",
        ],
        "validation": [
            "bash tools/smoke_central_brain_semantic_gateway.sh",
            "bash tools/smoke_central_brain_linux_ipc.sh",
            "bash tools/smoke_central_brain_linux_grpc.sh",
        ],
        "blocked_by": [
            "subscription broker owner and lifecycle persistence decision",
            "activation evidence retention owner, URI rule, delete/export, and gate closure authority decision",
            "push transport choice for Android callback, Linux watch, SSE/WebSocket, or DDS",
            "target high-rate topic QoS, replay, and overflow policy",
        ],
        "req_ids": ["DEL-001", "DEL-002", "XSC-002", "XSC-006", "FW-U-003", "NV-P-002", "NV-P-003", "NV-P-006"],
    },
    {
        "target": "linux-systemd-package-profile",
        "platform": "Linux",
        "current_state": "sample-profile-and-hardening-check",
        "ready_for": ["target distro review", "systemd sandbox review", "package layout discussion"],
        "artifacts": [
            "central-brain/deploy/linux/central-brain.package-profile.json",
            "central-brain/deploy/linux/systemd/central-brain-backend.service",
            "central-brain/deploy/linux/systemd/central-brain-governance.service",
            "central-brain/deploy/linux/systemd/central-brain-linux-ipc.service",
            "central-brain/deploy/linux/systemd/central-brain-linux-grpc.service",
        ],
        "validation": [
            "bash tools/check_central_brain_linux_package_profile.sh",
            "bash tools/check_central_brain_linux_systemd_hardening.sh",
        ],
        "blocked_by": [
            "target distro/package format decision",
            "LSM/SELinux/AppArmor policy for target image",
        ],
        "req_ids": ["DEL-002", "DEL-003", "DEL-004", "XSC-005", "XSC-006", "NV-P-002", "NV-P-003"],
    },
    {
        "target": "driver-hal-gap-backlog",
        "platform": "Android/Linux",
        "current_state": "read-only-gap-contract",
        "ready_for": ["hardware/vendor SDK intake", "Driver/HAL scope review"],
        "artifacts": [
            "docs/CENTRAL_BRAIN_DRIVER_INTERFACE_SUPPORT.md",
            "docs/CENTRAL_BRAIN_NPU_RUNTIME_INTERFACE.md",
            "GET /native/driver-gaps",
        ],
        "validation": ["bash tools/check_central_brain_npu_interface.sh"],
        "blocked_by": [
            "real PCIe NPU hardware and vendor SDK",
            "target vehicle signal catalog, DBC/ARXML, or VHAL contract",
        ],
        "req_ids": ["DEL-005", "XSC-004", "KH-003", "KH-006", "KH-007", "HW-002", "NV-F-011"],
    },
    {
        "target": "hardware-empty-interface-registry",
        "platform": "Android/Linux",
        "current_state": "read-only-empty-interface-activation-checklist-owner-decision-status-evidence-intake-status-retention-closure-replacement-trigger-selected-adapter-readiness-adapter-load-blocker-rollup-adapter-load-dry-run-status-audit-consistency-approval-authority-and-approval-authority-audit-consistency-contract",
        "ready_for": [
            "hardware interface review",
            "hardware activation checklist review",
            "hardware owner decision status review",
            "hardware owner decision evidence intake review",
            "hardware owner decision evidence status review",
            "hardware owner decision evidence retention and closure checklist review",
            "hardware owner evidence replacement trigger checklist review",
            "hardware owner evidence selected-adapter readiness checklist review",
            "hardware owner evidence adapter load blocker rollup review",
            "hardware owner evidence adapter load dry-run request review",
            "hardware owner evidence adapter load dry-run no-store status review",
            "hardware owner evidence adapter load dry-run audit consistency review",
            "hardware owner evidence adapter load approval authority checklist review",
            "hardware owner evidence adapter load approval authority no-store status review",
            "hardware owner evidence adapter load approval authority audit consistency review",
            "future Driver/HAL adapter planning",
            "Android/Linux cockpit-domain inspection",
        ],
        "artifacts": [
            "central-brain/backend/hardware_interfaces.py",
            "GET /hardware/interfaces",
            "GET /hardware/interfaces/activation-checklist",
            "GET /hardware/interfaces/owner-decision-status",
            "POST /hardware/interfaces/owner-decision-evidence",
            "GET /hardware/interfaces/owner-decision-evidence/status",
            "GET /hardware/interfaces/owner-decision-evidence/retention-checklist",
            "GET /hardware/interfaces/owner-decision-evidence/replacement-trigger-checklist",
            "GET /hardware/interfaces/owner-decision-evidence/selected-adapter-readiness-checklist",
            "GET /hardware/interfaces/owner-decision-evidence/adapter-load-blocker-rollup",
            "POST /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run",
            "GET /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/status",
            "GET /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/audit-consistency",
            "GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist",
            "GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/status",
            "GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/audit-consistency",
            "Android Binder getHardwareInterfacesJson",
            "Android Binder getHardwareInterfaceActivationChecklistJson",
            "Android Binder getHardwareInterfaceOwnerDecisionStatusJson",
            "Android Binder submitHardwareInterfaceOwnerDecisionEvidenceJson",
            "Android Binder getHardwareInterfaceOwnerDecisionEvidenceStatusJson",
            "Android Binder getHardwareInterfaceOwnerDecisionEvidenceRetentionChecklistJson",
            "Android Binder getHardwareInterfaceOwnerDecisionEvidenceReplacementTriggerChecklistJson",
            "Android Binder getHardwareInterfaceOwnerDecisionEvidenceSelectedAdapterReadinessChecklistJson",
            "Android Binder getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadBlockerRollupJson",
            "Android Binder dryRunHardwareInterfaceOwnerDecisionEvidenceAdapterLoadJson",
            "Android Binder getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadDryRunStatusJson",
            "Android Binder getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadDryRunAuditConsistencyJson",
            "Android Binder getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityChecklistJson",
            "Android Binder getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityStatusJson",
            "Android Binder getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityAuditConsistencyJson",
            "Linux CLI hardware-interfaces",
            "Linux CLI hardware-interface-activation-checklist",
            "Linux CLI hardware-interface-owner-decision-status",
            "Linux CLI hardware-interface-owner-decision-evidence",
            "Linux CLI hardware-interface-owner-decision-evidence-status",
            "Linux CLI hardware-interface-owner-decision-evidence-retention-checklist",
            "Linux CLI hardware-interface-owner-decision-evidence-replacement-trigger-checklist",
            "Linux CLI hardware-interface-owner-decision-evidence-selected-adapter-readiness-checklist",
            "Linux CLI hardware-interface-owner-decision-evidence-adapter-load-blocker-rollup",
            "Linux CLI hardware-interface-owner-decision-evidence-adapter-load-dry-run",
            "Linux CLI hardware-interface-owner-decision-evidence-adapter-load-dry-run-status",
            "Linux CLI hardware-interface-owner-decision-evidence-adapter-load-dry-run-audit-consistency",
            "Linux CLI hardware-interface-owner-decision-evidence-adapter-load-approval-authority-checklist",
            "Linux CLI hardware-interface-owner-decision-evidence-adapter-load-approval-authority-status",
            "Linux CLI hardware-interface-owner-decision-evidence-adapter-load-approval-authority-audit-consistency",
            "Linux IPC hardware.interfaces.get",
            "Linux IPC hardware.interfaces.activation.checklist",
            "Linux IPC hardware.interfaces.owner.decision.status",
            "Linux IPC hardware.interfaces.owner.decision.evidence",
            "Linux IPC hardware.interfaces.owner.decision.evidence.status",
            "Linux IPC hardware.interfaces.owner.decision.evidence.retention.checklist",
            "Linux IPC hardware.interfaces.owner.decision.evidence.replacement.trigger.checklist",
            "Linux IPC hardware.interfaces.owner.decision.evidence.selected.adapter.readiness.checklist",
            "Linux IPC hardware.interfaces.owner.decision.evidence.adapter.load.blocker.rollup",
            "Linux IPC hardware.interfaces.owner.decision.evidence.adapter.load.dry.run",
            "Linux IPC hardware.interfaces.owner.decision.evidence.adapter.load.dry.run.status",
            "Linux IPC hardware.interfaces.owner.decision.evidence.adapter.load.dry.run.audit.consistency",
            "Linux IPC hardware.interfaces.owner.decision.evidence.adapter.load.approval.authority.checklist",
            "Linux IPC hardware.interfaces.owner.decision.evidence.adapter.load.approval.authority.status",
            "Linux IPC hardware.interfaces.owner.decision.evidence.adapter.load.approval.authority.audit.consistency",
            "Linux gRPC/RPC GetHardwareInterfaces",
            "Linux gRPC/RPC GetHardwareInterfaceActivationChecklist",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionStatus",
            "Linux gRPC/RPC SubmitHardwareInterfaceOwnerDecisionEvidence",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionEvidenceStatus",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionEvidenceRetentionChecklist",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionEvidenceReplacementTriggerChecklist",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionEvidenceSelectedAdapterReadinessChecklist",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadBlockerRollup",
            "Linux gRPC/RPC DryRunHardwareInterfaceOwnerDecisionEvidenceAdapterLoad",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadDryRunStatus",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadDryRunAuditConsistency",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityChecklist",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityStatus",
            "Linux gRPC/RPC GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityAuditConsistency",
        ],
        "validation": [
            "bash tools/smoke_central_brain_semantic_gateway.sh",
            "bash tools/smoke_central_brain_linux_ipc.sh",
            "bash tools/smoke_central_brain_linux_grpc.sh",
        ],
        "blocked_by": [
            "target interface owner, ABI, safety policy, smoke evidence, retention, review, delete/export, gate closure, replacement trigger, selected-adapter readiness, adapter-load blocker, adapter-load dry-run approval, dry-run status persistence, dry-run audit consistency, adapter-load approval authority decisions, and approval authority audit consistency",
            "real PCIe NPU hardware and vendor SDK",
            "target vehicle signal catalog, DBC/ARXML, VHAL contract, or gateway",
            "target sensor/network/shared-memory/Safety Runtime owner decisions",
        ],
        "req_ids": ["DEL-001", "DEL-002", "DEL-005", "XSC-004", "XSC-006", "HW-002", "KH-001", "KH-002", "KH-003", "KH-006", "KH-007"],
    },
    {
        "target": "vehicle-signal-catalog-contract",
        "platform": "Android/Linux",
        "current_state": "read-only-signal-catalog-contract",
        "ready_for": ["Vehicle/Body Signal catalog review", "future DBC/ARXML or VHAL activation planning", "Android/Linux cockpit-domain inspection"],
        "artifacts": [
            "central-brain/backend/vehicle_signals.py",
            "GET /vehicle/signals",
            "Android Binder getVehicleSignalsJson",
            "Linux CLI vehicle-signals",
            "Linux IPC vehicle.signals.list",
            "Linux gRPC/RPC GetVehicleSignals",
        ],
        "validation": [
            "bash tools/smoke_central_brain_semantic_gateway.sh",
            "bash tools/smoke_central_brain_linux_ipc.sh",
            "bash tools/smoke_central_brain_linux_grpc.sh",
        ],
        "blocked_by": [
            "target vehicle signal catalog, DBC/ARXML, VHAL contract, SocketCAN, or vendor gateway",
            "Vehicle Signal Adapter owner decision for read bridge activation",
        ],
        "req_ids": ["DEL-001", "DEL-002", "DEL-005", "XSC-002", "XSC-004", "XSC-006", "NV-F-004", "NV-F-005", "NV-P-002", "NV-P-003"],
    },
    {
        "target": "vehicle-signal-activation-criteria",
        "platform": "Android/Linux",
        "current_state": "criteria-only-not-activated",
        "ready_for": [
            "Vehicle Signal read-bridge activation review",
            "DBC/ARXML, Android VHAL/vendor AIDL, Linux SocketCAN, or vendor gateway intake planning",
            "Driver/HAL scope triage before any real bridge work",
        ],
        "artifacts": [
            "central-brain/backend/vehicle_signals.py",
            "GET /vehicle/signals/activation",
            "Android Binder getVehicleSignalActivationJson",
            "Linux CLI vehicle-signal-activation",
            "Linux IPC vehicle.signals.activation.get",
            "Linux gRPC/RPC GetVehicleSignalActivation",
        ],
        "validation": [
            "bash tools/smoke_central_brain_semantic_gateway.sh",
            "bash tools/smoke_central_brain_linux_ipc.sh",
            "bash tools/smoke_central_brain_linux_grpc.sh",
        ],
        "blocked_by": [
            "target vehicle DBC/ARXML, Android VHAL/vendor AIDL, Linux SocketCAN, or vendor gateway source",
            "Vehicle Signal Adapter owner decision for schema validation and read bridge activation",
            "Driver/HAL scope review if target environment cannot provide existing user-space bridge APIs",
        ],
        "req_ids": ["DEL-001", "DEL-002", "DEL-005", "XSC-002", "XSC-004", "XSC-006", "NV-F-003", "NV-F-004", "NV-F-005", "NV-P-001", "NV-P-002", "NV-P-003", "KH-003", "KH-006", "KH-007"],
    },
    {
        "target": "vehicle-signal-validation-envelope",
        "platform": "Android/Linux",
        "current_state": "metadata-only-not-activated",
        "ready_for": [
            "Vehicle Signal schema-source metadata intake checklist review",
            "adapter owner and ABI owner assignment review",
            "Android/Linux parity and DRV-GAP-002 evidence planning before any real read bridge work",
        ],
        "artifacts": [
            "central-brain/backend/vehicle_signals.py",
            "GET /vehicle/signals/validation",
            "Android Binder getVehicleSignalValidationJson",
            "Linux CLI vehicle-signal-validation",
            "Linux IPC vehicle.signals.validation.get",
            "Linux gRPC/RPC GetVehicleSignalValidation",
        ],
        "validation": [
            "bash tools/smoke_central_brain_semantic_gateway.sh",
            "bash tools/smoke_central_brain_linux_ipc.sh",
            "bash tools/smoke_central_brain_linux_grpc.sh",
        ],
        "blocked_by": [
            "target DBC/ARXML, Android VHAL/vendor AIDL, Linux SocketCAN, SOME/IP, or vendor gateway source metadata",
            "Vehicle Signal Adapter owner and platform ABI/API owner assignment",
            "DRV-GAP-002 owner, ABI, minimal implementation scope, and validation smoke evidence",
        ],
        "req_ids": ["DEL-001", "DEL-002", "DEL-005", "XSC-002", "XSC-004", "XSC-006", "NV-F-003", "NV-F-004", "NV-F-005", "NV-P-001", "NV-P-002", "NV-P-003", "KH-003", "KH-006", "KH-007"],
    },
    {
        "target": "virtualization-safety-constraints",
        "platform": "Android/Linux",
        "current_state": "documented-non-development-scope",
        "ready_for": ["Safety State mapping review", "ASIL/QM deployment assumption review"],
        "artifacts": ["docs/CENTRAL_BRAIN_VIRTUALIZATION_SAFETY_CONSTRAINTS.md"],
        "validation": ["bash tools/check_central_brain_virtualization_docs.sh"],
        "blocked_by": ["target SoC/hypervisor safety-domain definition"],
        "req_ids": ["DEL-004", "HV-001", "HV-002", "HV-003", "FW-S-005", "NV-G-005"],
    },
]


def delivery_readiness_payload() -> dict[str, Any]:
    rows = copy.deepcopy(DELIVERY_READINESS_ROWS)
    return {
        "readiness": rows,
        "summary": {
            "production_ready": False,
            "android_debug_ready": True,
            "linux_samples_ready": True,
            "driver_development_triggered": False,
            "virtualization_development_triggered": False,
            "service_dispatch_triggered": False,
            "target_decisions_required": [
                "AAOS signing/SELinux/service owner",
                "target Linux distro/package format",
                "true gRPC runtime and credential source",
                "production shared governance backend owner",
                "real Driver/HAL hardware and vendor SDK inputs",
            ],
        },
        "non_goals": [
            "No production Android system service, true gRPC runtime, package manager integration, Driver/HAL, Safety Runtime, vehicle bus, or virtualization code is implemented by this readiness contract.",
            "This endpoint does not dispatch SOA services or consume QoS; it is delivery metadata for cockpit-domain engineers.",
        ],
        "validation_bundle": sorted({command for row in rows for command in row["validation"]}),
        "req_ids": DELIVERY_REQ_IDS,
    }
