#!/usr/bin/env python3
"""Protocol Binding registry for the Central Brain prototype."""

from __future__ import annotations

import copy
from typing import Any


BINDING_REQ_IDS = [
    "XSC-006",
    "NV-P-001",
    "NV-P-002",
    "NV-P-003",
    "NV-P-004",
    "NV-P-005",
    "NV-P-006",
]

BINDING_READINESS_ROWS: list[dict[str, Any]] = [
    {
        "binding": "android-binder-aidl",
        "platform": "Android",
        "current_state": "service-stub-sample",
        "ready_for": ["debug APK integration", "AIDL contract review", "system-service planning"],
        "blocked_by": [
            "target AAOS signing and priv-app policy",
            "SELinux domain and service manager registration decision",
            "production shared Runtime & Governance backend owner",
        ],
        "validation": [
            "bash tools/check_central_brain_binding_artifacts.sh",
            "bash tools/build_central_brain_console.sh",
            "bash tools/check_central_brain_android_system_service_docs.sh",
        ],
        "req_ids": ["XSC-006", "NV-P-002", "DEL-001", "DEL-003", "DEL-004"],
    },
    {
        "binding": "linux-ipc",
        "platform": "Linux",
        "current_state": "active-sample",
        "ready_for": ["Unix socket local integration", "shared governance precheck sample", "systemd sample review"],
        "blocked_by": [
            "target distro package format and service identity decision",
            "production shared governance daemon replacement",
            "LSM/SELinux/AppArmor policy for target image",
        ],
        "validation": [
            "bash tools/smoke_central_brain_linux_ipc.sh",
            "bash tools/check_central_brain_linux_package_profile.sh",
            "bash tools/check_central_brain_linux_systemd_hardening.sh",
        ],
        "req_ids": ["XSC-006", "NV-P-002", "XSC-005", "DEL-002", "DEL-003", "DEL-004"],
    },
    {
        "binding": "linux-grpc-rpc",
        "platform": "Linux",
        "current_state": "grpc-json-active-sample",
        "ready_for": ["proto contract review", "JSON TCP contract smoke", "shared governance precheck sample"],
        "blocked_by": [
            "grpcio or C++ gRPC target runtime availability",
            "credential source for production RPC calls",
            "production shared governance backend replacement",
        ],
        "validation": [
            "bash tools/smoke_central_brain_linux_grpc.sh",
            "bash tools/check_central_brain_binding_artifacts.sh",
        ],
        "req_ids": ["XSC-006", "NV-P-003", "XSC-005", "DEL-002", "DEL-004"],
    },
    {
        "binding": "rest-http-json",
        "platform": "Android emulator/Linux host",
        "current_state": "active-prototype",
        "ready_for": ["semantic gateway smoke", "contract reference", "prototype fallback"],
        "blocked_by": [
            "replacement by Android Binder, Linux IPC, or true gRPC in production paths",
            "service identity and policy source for non-debug deployment",
        ],
        "validation": [
            "bash tools/smoke_central_brain_semantic_gateway.sh",
            "python3 -m json.tool central-brain/contracts/central_brain_api.json",
        ],
        "req_ids": ["XSC-002", "XSC-003", "XSC-005", "XSC-006", "NV-P-005", "DEL-001", "DEL-002"],
    },
    {
        "binding": "mqtt",
        "platform": "Android/Linux",
        "current_state": "planned-policy-gated",
        "ready_for": ["privacy and policy contract discussion"],
        "blocked_by": [
            "cloud vehicle-message broker selection",
            "privacy routing and audit export policy",
        ],
        "validation": ["GET /bindings/readiness"],
        "req_ids": ["XSC-006", "NV-P-004", "DEL-004"],
    },
    {
        "binding": "someip",
        "platform": "Linux/vehicle network",
        "current_state": "planned-after-vehicle-network",
        "ready_for": ["vehicle network integration planning"],
        "blocked_by": [
            "target vehicle service discovery stack",
            "DBC/ARXML or service catalog source",
        ],
        "validation": ["GET /bindings/readiness"],
        "req_ids": ["XSC-006", "NV-P-001", "DEL-004"],
    },
    {
        "binding": "dds",
        "platform": "Linux/Android native",
        "current_state": "planned-for-high-rate-topics",
        "ready_for": ["high-rate event data-plane planning"],
        "blocked_by": [
            "DDS vendor/runtime selection",
            "high-frequency topic QoS and backpressure requirements",
            "shared memory/Safety Runtime constraints for target platform",
        ],
        "validation": ["GET /bindings/readiness"],
        "req_ids": ["XSC-006", "NV-P-006", "FW-U-003", "DEL-004"],
    },
]

BINDING_REGISTRY: list[dict[str, Any]] = [
    {
        "name": "rest-http-json",
        "status": "active-prototype",
        "platforms": ["Android emulator", "Linux host"],
        "semantic_paths": [
            "/uib/context",
            "/uib/state",
            "/uib/events/topics",
            "/uib/events/publish",
            "/uib/events/recent",
            "/uib/events/subscriptions",
            "/uib/events/subscriptions/request",
            "/uib/events/subscriptions/cancel",
            "/uib/events/subscriptions/transport-readiness",
            "/uib/events/subscriptions/decision-matrix",
            "/uib/events/subscriptions/activation-checklist",
            "/uib/events/subscriptions/callback-watch-shape",
            "/uib/events/subscriptions/cursor-replay-storage",
            "/uib/events/subscriptions/backpressure-qos-evidence",
            "/uib/events/subscriptions/readiness-rollup",
            "/uib/events/subscriptions/activation-evidence",
            "/uib/events/subscriptions/activation-evidence/status",
            "/uib/events/subscriptions/activation-evidence/retention-checklist",
            "/uib/events/subscriptions/activation-evidence/decision-status-rollup",
            "/uib/events/subscriptions/activation-evidence/approval-dry-run/status",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/audit-consistency",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-blocker-rollup",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/status",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/audit-consistency",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup/handoff-evidence-readiness-matrix",
            "/uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup/handoff-evidence-readiness-matrix/audit-consistency",
            "/uib/extensions",
            "/uib/actions/request",
            "/ai/sdk/capabilities",
            "/agent/plan",
            "/agent/execute",
            "/skills",
            "/skills/{skill_id}/invoke",
            "/memory/query",
            "/soa/services",
            "/soa/invoke",
            "/governance/precheck",
            "/governance/backend-contract",
            "/governance/migration-check",
            "/governance/deployment-plan",
            "/native/driver-gaps",
            "/hardware/interfaces",
            "/hardware/interfaces/activation-checklist",
            "/hardware/interfaces/owner-decision-status",
            "/hardware/interfaces/owner-decision-evidence",
            "/hardware/interfaces/owner-decision-evidence/status",
            "/hardware/interfaces/owner-decision-evidence/retention-checklist",
            "/hardware/interfaces/owner-decision-evidence/replacement-trigger-checklist",
            "/hardware/interfaces/owner-decision-evidence/selected-adapter-readiness-checklist",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-blocker-rollup",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-dry-run",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/status",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/audit-consistency",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/status",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/audit-consistency",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/status",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/audit-consistency",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/audit-consistency",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist",
            "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency",
            "/vehicle/signals",
            "/vehicle/signals/activation",
            "/vehicle/signals/validation",
            "/soa/contracts",
            "/bindings/readiness",
            "/delivery/readiness",
            "/prototype/readiness",
        ],
        "artifacts": ["central-brain/contracts/central_brain_api.json"],
        "req_ids": ["XSC-001", "XSC-002", "XSC-003", "XSC-004", "XSC-005", "XSC-006", "APP-004", "FW-U-003", "FW-U-004", "FW-U-008", "FW-S-004", "HW-002", "KH-001", "KH-002", "KH-003", "KH-006", "KH-007", "DEL-005", "NV-F-003", "NV-F-004", "NV-F-005", "NV-G-003", "NV-G-004", "NV-P-001", "NV-P-005", "NV-P-006"],
    },
    {
        "name": "android-binder-aidl",
        "status": "service-stub-sample",
        "platforms": ["Android"],
        "semantic_paths": [
            "getContextJson -> /uib/context",
            "getStateJson -> /uib/state",
            "listEventTopicsJson -> /uib/events/topics",
            "publishEventJson -> /uib/events/publish",
            "getRecentEventsJson -> /uib/events/recent",
            "getEventSubscriptionsJson -> /uib/events/subscriptions",
            "requestEventSubscriptionJson -> /uib/events/subscriptions/request",
            "cancelEventSubscriptionJson -> /uib/events/subscriptions/cancel",
            "getEventSubscriptionTransportReadinessJson -> /uib/events/subscriptions/transport-readiness",
            "getEventSubscriptionDecisionMatrixJson -> /uib/events/subscriptions/decision-matrix",
            "getEventSubscriptionActivationChecklistJson -> /uib/events/subscriptions/activation-checklist",
            "getEventSubscriptionCallbackWatchShapeJson -> /uib/events/subscriptions/callback-watch-shape",
            "getEventSubscriptionCursorReplayStorageJson -> /uib/events/subscriptions/cursor-replay-storage",
            "getEventSubscriptionBackpressureQosEvidenceJson -> /uib/events/subscriptions/backpressure-qos-evidence",
            "getEventSubscriptionReadinessRollupJson -> /uib/events/subscriptions/readiness-rollup",
            "submitEventSubscriptionActivationEvidenceJson -> /uib/events/subscriptions/activation-evidence",
            "getEventSubscriptionActivationEvidenceStatusJson -> /uib/events/subscriptions/activation-evidence/status",
            "getEventSubscriptionActivationEvidenceRetentionChecklistJson -> /uib/events/subscriptions/activation-evidence/retention-checklist",
            "getEventSubscriptionActivationEvidenceDecisionStatusRollupJson -> /uib/events/subscriptions/activation-evidence/decision-status-rollup",
            "getEventSubscriptionActivationApprovalDryRunStatusJson -> /uib/events/subscriptions/activation-evidence/approval-dry-run/status",
            "getEventSubscriptionActivationApprovalAuthorityChecklistJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist",
            "getEventSubscriptionActivationApprovalAuthorityAuditConsistencyJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/audit-consistency",
            "getEventSubscriptionActivationApprovalDecisionBlockerRollupJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-blocker-rollup",
            "dryRunEventSubscriptionActivationApprovalDecisionJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run",
            "getEventSubscriptionActivationApprovalDecisionDryRunStatusJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/status",
            "getEventSubscriptionActivationApprovalDecisionDryRunAuditConsistencyJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/audit-consistency",
            "getEventSubscriptionActivationApprovalDecisionClosureBlockerMatrixJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix",
            "getEventSubscriptionActivationApprovalDecisionOwnerHandoffChecklistJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist",
            "getEventSubscriptionActivationApprovalDecisionOwnerHandoffAuditConsistencyJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency",
            "getEventSubscriptionActivationApprovalDecisionOwnerHandoffDecisionRollupJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup",
            "getEventSubscriptionActivationApprovalDecisionOwnerHandoffEvidenceReadinessMatrixJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup/handoff-evidence-readiness-matrix",
            "getEventSubscriptionActivationApprovalDecisionOwnerHandoffEvidenceReadinessAuditConsistencyJson -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup/handoff-evidence-readiness-matrix/audit-consistency",
            "getUibExtensionsJson -> /uib/extensions",
            "getAiSdkCapabilitiesJson -> /ai/sdk/capabilities",
            "planAgentTaskJson -> /agent/plan",
            "executeAgentTaskJson -> /agent/execute",
            "listSkillsJson -> /skills",
            "invokeSkillJson -> /skills/{skill_id}/invoke",
            "queryMemoryJson -> /memory/query",
            "requestActionJson -> /uib/actions/request",
            "listServicesJson -> /soa/services",
            "getServiceContractsJson -> /soa/contracts",
            "invokeServiceJson -> /soa/invoke",
            "evaluatePolicyJson -> /policy/evaluate",
            "precheckGovernanceJson -> /governance/precheck",
            "getGovernanceBackendContractJson -> /governance/backend-contract",
            "getGovernanceMigrationCheckJson -> /governance/migration-check",
            "getGovernanceDeploymentPlanJson -> /governance/deployment-plan",
            "getRuntimeGovernanceJson -> /governance/runtime",
            "getRecentAuditJson -> /audit/recent",
            "listBindingsJson -> /bindings",
            "getBindingDetailJson -> /bindings/detail",
            "getBindingReadinessJson -> /bindings/readiness",
            "getDeliveryReadinessJson -> /delivery/readiness",
            "getPrototypeReadinessJson -> /prototype/readiness",
            "getNativeAdaptersDetailJson -> /native/adapters/detail",
            "getDriverHalGapsJson -> /native/driver-gaps",
            "getHardwareInterfacesJson -> /hardware/interfaces",
            "getHardwareInterfaceActivationChecklistJson -> /hardware/interfaces/activation-checklist",
            "getHardwareInterfaceOwnerDecisionStatusJson -> /hardware/interfaces/owner-decision-status",
            "submitHardwareInterfaceOwnerDecisionEvidenceJson -> /hardware/interfaces/owner-decision-evidence",
            "getHardwareInterfaceOwnerDecisionEvidenceStatusJson -> /hardware/interfaces/owner-decision-evidence/status",
            "getHardwareInterfaceOwnerDecisionEvidenceRetentionChecklistJson -> /hardware/interfaces/owner-decision-evidence/retention-checklist",
            "getHardwareInterfaceOwnerDecisionEvidenceReplacementTriggerChecklistJson -> /hardware/interfaces/owner-decision-evidence/replacement-trigger-checklist",
            "getHardwareInterfaceOwnerDecisionEvidenceSelectedAdapterReadinessChecklistJson -> /hardware/interfaces/owner-decision-evidence/selected-adapter-readiness-checklist",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadBlockerRollupJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-blocker-rollup",
            "dryRunHardwareInterfaceOwnerDecisionEvidenceAdapterLoadJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadDryRunStatusJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/status",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadDryRunAuditConsistencyJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/audit-consistency",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityChecklistJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityStatusJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/status",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityAuditConsistencyJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/audit-consistency",
            "dryRunHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionDryRunStatusJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/status",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionDryRunAuditConsistencyJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/audit-consistency",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionClosureBlockerMatrixJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionReviewerMatrixJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffChecklistJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceStatusJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceAuditConsistencyJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/audit-consistency",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceDecisionRollupJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessChecklistJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessAuditConsistencyJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessDecisionRollupJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessDecisionReviewerAssignmentChecklistJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessDecisionReviewerAssignmentAuditConsistencyJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessDecisionReviewerAssignmentAuditDecisionRollupJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency/decision-rollup",
            "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessDecisionReviewerAssignmentAuditDecisionRollupClosureHandoffReadinessSummaryJson -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency/decision-rollup/closure-handoff-readiness-summary",
            "getVehicleSignalsJson -> /vehicle/signals",
            "getVehicleSignalActivationJson -> /vehicle/signals/activation",
            "getVehicleSignalValidationJson -> /vehicle/signals/validation",
        ],
        "artifacts": [
            "central-brain/bindings/android/aidl/com/centralbrain/binding/ICentralBrainGateway.aidl",
            "central-brain/bindings/android/java/com/centralbrain/binding/CentralBrainGatewayBinderService.java",
            "central-brain/bindings/android/java/com/centralbrain/binding/CentralBrainGatewayClient.java",
            "central-brain/bindings/android/README.md",
            "docs/CENTRAL_BRAIN_ANDROID_SYSTEM_SERVICE_INTEGRATION.md",
        ],
        "req_ids": ["XSC-001", "XSC-002", "XSC-003", "XSC-004", "XSC-005", "XSC-006", "APP-004", "FW-U-003", "FW-U-004", "FW-U-007", "FW-U-008", "FW-S-004", "FW-S-005", "HW-002", "KH-001", "KH-002", "KH-003", "KH-006", "KH-007", "DEL-005", "NV-F-003", "NV-F-004", "NV-F-005", "NV-G-002", "NV-G-003", "NV-G-004", "NV-G-005", "NV-G-006", "NV-G-007", "NV-P-001", "NV-P-002", "NV-P-005", "NV-P-006", "DEL-001", "DEL-003", "DEL-004"],
    },
    {
        "name": "linux-ipc",
        "status": "active-sample",
        "platforms": ["Linux"],
        "semantic_paths": [
            "uib.context.get -> /uib/context",
            "uib.state.get -> /uib/state",
            "uib.events.topics -> /uib/events/topics",
            "uib.events.publish -> /uib/events/publish",
            "uib.events.recent -> /uib/events/recent",
            "uib.events.subscriptions.get -> /uib/events/subscriptions",
            "uib.events.subscriptions.request -> /uib/events/subscriptions/request",
            "uib.events.subscriptions.cancel -> /uib/events/subscriptions/cancel",
            "uib.events.subscriptions.transport.readiness -> /uib/events/subscriptions/transport-readiness",
            "uib.events.subscriptions.decision.matrix -> /uib/events/subscriptions/decision-matrix",
            "uib.events.subscriptions.activation.checklist -> /uib/events/subscriptions/activation-checklist",
            "uib.events.subscriptions.callback.watch.shape -> /uib/events/subscriptions/callback-watch-shape",
            "uib.events.subscriptions.cursor.replay.storage -> /uib/events/subscriptions/cursor-replay-storage",
            "uib.events.subscriptions.backpressure.qos.evidence -> /uib/events/subscriptions/backpressure-qos-evidence",
            "uib.events.subscriptions.readiness.rollup -> /uib/events/subscriptions/readiness-rollup",
            "uib.events.subscriptions.activation.evidence -> /uib/events/subscriptions/activation-evidence",
            "uib.events.subscriptions.activation.evidence.status -> /uib/events/subscriptions/activation-evidence/status",
            "uib.events.subscriptions.activation.evidence.retention.checklist -> /uib/events/subscriptions/activation-evidence/retention-checklist",
            "uib.events.subscriptions.activation.evidence.decision.status.rollup -> /uib/events/subscriptions/activation-evidence/decision-status-rollup",
            "uib.events.subscriptions.activation.approval.dry.run.status -> /uib/events/subscriptions/activation-evidence/approval-dry-run/status",
            "uib.events.subscriptions.activation.approval.authority.checklist -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist",
            "uib.events.subscriptions.activation.approval.authority.audit.consistency -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/audit-consistency",
            "uib.events.subscriptions.activation.approval.decision.blocker.rollup -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-blocker-rollup",
            "uib.events.subscriptions.activation.approval.decision.dry.run -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run",
            "uib.events.subscriptions.activation.approval.decision.dry.run.status -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/status",
            "uib.events.subscriptions.activation.approval.decision.dry.run.audit.consistency -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/audit-consistency",
            "uib.events.subscriptions.activation.approval.decision.closure.blocker.matrix -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix",
            "uib.events.subscriptions.activation.approval.decision.owner.handoff.checklist -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist",
            "uib.events.subscriptions.activation.approval.decision.owner.handoff.audit.consistency -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency",
            "uib.events.subscriptions.activation.approval.decision.owner.handoff.decision.rollup -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup",
            "uib.events.subscriptions.activation.approval.decision.owner.handoff.evidence.readiness.matrix -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup/handoff-evidence-readiness-matrix",
            "uib.events.subscriptions.activation.approval.decision.owner.handoff.evidence.readiness.audit.consistency -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup/handoff-evidence-readiness-matrix/audit-consistency",
            "uib.extensions.get -> /uib/extensions",
            "uib.actions.request -> /uib/actions/request",
            "ai.sdk.capabilities -> /ai/sdk/capabilities",
            "agent.plan -> /agent/plan",
            "agent.execute -> /agent/execute",
            "skills.list -> /skills",
            "skills.invoke -> /skills/{skill_id}/invoke",
            "memory.query -> /memory/query",
            "soa.services.list -> /soa/services",
            "soa.contracts.get -> /soa/contracts",
            "soa.service.invoke -> shared Linux governance daemon precheck with local fallback -> /soa/invoke",
            "policy.evaluate -> /policy/evaluate",
            "governance.precheck -> /governance/precheck or direct shared governance socket",
            "governance.backend.contract.get -> /governance/backend-contract",
            "governance.migration.check -> /governance/migration-check",
            "governance.deployment.plan.get -> /governance/deployment-plan",
            "governance.runtime.get -> shared governance socket diagnostic with REST gateway fallback",
            "audit.recent.get -> shared governance socket diagnostic with REST gateway fallback",
            "bindings.list -> /bindings",
            "bindings.readiness.get -> /bindings/readiness",
            "delivery.readiness.get -> /delivery/readiness",
            "prototype.readiness.get -> /prototype/readiness",
            "hardware.interfaces.get -> /hardware/interfaces",
            "hardware.interfaces.activation.checklist -> /hardware/interfaces/activation-checklist",
            "hardware.interfaces.owner.decision.status -> /hardware/interfaces/owner-decision-status",
            "hardware.interfaces.owner.decision.evidence -> /hardware/interfaces/owner-decision-evidence",
            "hardware.interfaces.owner.decision.evidence.status -> /hardware/interfaces/owner-decision-evidence/status",
            "hardware.interfaces.owner.decision.evidence.retention.checklist -> /hardware/interfaces/owner-decision-evidence/retention-checklist",
            "hardware.interfaces.owner.decision.evidence.replacement.trigger.checklist -> /hardware/interfaces/owner-decision-evidence/replacement-trigger-checklist",
            "hardware.interfaces.owner.decision.evidence.selected.adapter.readiness.checklist -> /hardware/interfaces/owner-decision-evidence/selected-adapter-readiness-checklist",
            "hardware.interfaces.owner.decision.evidence.adapter.load.blocker.rollup -> /hardware/interfaces/owner-decision-evidence/adapter-load-blocker-rollup",
            "hardware.interfaces.owner.decision.evidence.adapter.load.dry.run -> /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run",
            "hardware.interfaces.owner.decision.evidence.adapter.load.dry.run.status -> /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/status",
            "hardware.interfaces.owner.decision.evidence.adapter.load.dry.run.audit.consistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/audit-consistency",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.authority.checklist -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.authority.status -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/status",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.authority.audit.consistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/audit-consistency",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.decision.dry.run -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.decision.dry.run.status -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/status",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.decision.dry.run.audit.consistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/audit-consistency",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.decision.closure.blocker.matrix -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.decision.reviewer.matrix -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.checklist -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.acceptance.status -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.acceptance.audit.consistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/audit-consistency",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.acceptance.decision.rollup -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.acceptance.closure.readiness.checklist -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.acceptance.closure.readiness.audit.consistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.acceptance.closure.readiness.decision.rollup -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.acceptance.closure.readiness.decision.reviewer.assignment.checklist -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.acceptance.closure.readiness.decision.reviewer.assignment.audit.consistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.acceptance.closure.readiness.decision.reviewer.assignment.audit.decision.rollup -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency/decision-rollup",
            "hardware.interfaces.owner.decision.evidence.adapter.load.approval.reviewer.evidence.handoff.acceptance.closure.readiness.decision.reviewer.assignment.audit.decision.rollup.closure.handoff.readiness.summary -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency/decision-rollup/closure-handoff-readiness-summary",
            "vehicle.signals.list -> /vehicle/signals",
            "vehicle.signals.activation.get -> /vehicle/signals/activation",
            "vehicle.signals.validation.get -> /vehicle/signals/validation",
        ],
        "artifacts": [
            "central-brain/bindings/linux/ipc/central_brain_ipc_envelope.schema.json",
            "central-brain/bindings/linux/ipc/central_brain_governance_daemon.py",
            "central-brain/bindings/linux/ipc/central_brain_governance_client.py",
            "central-brain/bindings/linux/ipc/central_brain_ipc_daemon.py",
            "central-brain/bindings/linux/ipc/central_brain_ipc_client.py",
            "central-brain/bindings/linux/README.md",
        ],
        "req_ids": ["XSC-001", "XSC-002", "XSC-003", "XSC-004", "XSC-005", "XSC-006", "APP-004", "FW-U-003", "FW-U-004", "FW-U-008", "FW-S-004", "HW-002", "KH-001", "KH-002", "KH-003", "KH-006", "KH-007", "DEL-005", "NV-F-003", "NV-F-004", "NV-F-005", "NV-G-002", "NV-G-003", "NV-G-004", "NV-G-005", "NV-G-006", "NV-G-007", "NV-P-001", "NV-P-002", "NV-P-006", "DEL-002"],
    },
    {
        "name": "grpc",
        "status": "grpc-json-active-sample",
        "platforms": ["Android", "Linux"],
        "semantic_paths": [
            "CentralBrainGateway.GetContext -> /uib/context",
            "CentralBrainGateway.GetState -> /uib/state",
            "CentralBrainGateway.ListEventTopics -> /uib/events/topics",
            "CentralBrainGateway.PublishEvent -> /uib/events/publish",
            "CentralBrainGateway.GetRecentEvents -> /uib/events/recent",
            "CentralBrainGateway.GetEventSubscriptions -> /uib/events/subscriptions",
            "CentralBrainGateway.RequestEventSubscription -> /uib/events/subscriptions/request",
            "CentralBrainGateway.CancelEventSubscription -> /uib/events/subscriptions/cancel",
            "CentralBrainGateway.GetEventSubscriptionTransportReadiness -> /uib/events/subscriptions/transport-readiness",
            "CentralBrainGateway.GetEventSubscriptionDecisionMatrix -> /uib/events/subscriptions/decision-matrix",
            "CentralBrainGateway.GetEventSubscriptionActivationChecklist -> /uib/events/subscriptions/activation-checklist",
            "CentralBrainGateway.GetEventSubscriptionCallbackWatchShape -> /uib/events/subscriptions/callback-watch-shape",
            "CentralBrainGateway.GetEventSubscriptionCursorReplayStorage -> /uib/events/subscriptions/cursor-replay-storage",
            "CentralBrainGateway.GetEventSubscriptionBackpressureQosEvidence -> /uib/events/subscriptions/backpressure-qos-evidence",
            "CentralBrainGateway.GetEventSubscriptionReadinessRollup -> /uib/events/subscriptions/readiness-rollup",
            "CentralBrainGateway.SubmitEventSubscriptionActivationEvidence -> /uib/events/subscriptions/activation-evidence",
            "CentralBrainGateway.GetEventSubscriptionActivationEvidenceStatus -> /uib/events/subscriptions/activation-evidence/status",
            "CentralBrainGateway.GetEventSubscriptionActivationEvidenceRetentionChecklist -> /uib/events/subscriptions/activation-evidence/retention-checklist",
            "CentralBrainGateway.GetEventSubscriptionActivationEvidenceDecisionStatusRollup -> /uib/events/subscriptions/activation-evidence/decision-status-rollup",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalDryRunStatus -> /uib/events/subscriptions/activation-evidence/approval-dry-run/status",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalAuthorityChecklist -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalAuthorityAuditConsistency -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/audit-consistency",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalDecisionBlockerRollup -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-blocker-rollup",
            "CentralBrainGateway.DryRunEventSubscriptionActivationApprovalDecision -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalDecisionDryRunStatus -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/status",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalDecisionDryRunAuditConsistency -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/audit-consistency",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalDecisionClosureBlockerMatrix -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalDecisionOwnerHandoffChecklist -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalDecisionOwnerHandoffAuditConsistency -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalDecisionOwnerHandoffDecisionRollup -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalDecisionOwnerHandoffEvidenceReadinessMatrix -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup/handoff-evidence-readiness-matrix",
            "CentralBrainGateway.GetEventSubscriptionActivationApprovalDecisionOwnerHandoffEvidenceReadinessAuditConsistency -> /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency/decision-rollup/handoff-evidence-readiness-matrix/audit-consistency",
            "CentralBrainGateway.GetUibExtensions -> /uib/extensions",
            "CentralBrainGateway.GetAiSdkCapabilities -> /ai/sdk/capabilities",
            "CentralBrainGateway.PlanAgentTask -> /agent/plan",
            "CentralBrainGateway.ExecuteAgentTask -> /agent/execute",
            "CentralBrainGateway.ListSkills -> /skills",
            "CentralBrainGateway.InvokeSkill -> /skills/{skill_id}/invoke",
            "CentralBrainGateway.QueryMemory -> /memory/query",
            "CentralBrainGateway.RequestAction -> /uib/actions/request",
            "CentralBrainGateway.ListServices -> /soa/services",
            "CentralBrainGateway.GetServiceContracts -> /soa/contracts",
            "CentralBrainGateway.InvokeService -> /soa/invoke",
            "CentralBrainGateway.EvaluatePolicy -> /policy/evaluate",
            "CentralBrainGateway.PrecheckGovernance -> /governance/precheck",
            "CentralBrainGateway.GetGovernanceBackendContract -> /governance/backend-contract",
            "CentralBrainGateway.GetGovernanceMigrationCheck -> /governance/migration-check",
            "CentralBrainGateway.GetGovernanceDeploymentPlan -> /governance/deployment-plan",
            "CentralBrainGateway.GetRuntimeGovernance -> shared governance socket diagnostic with REST gateway fallback",
            "CentralBrainGateway.GetRecentAudit -> shared governance socket diagnostic with REST gateway fallback",
            "CentralBrainGateway.ListBindings -> /bindings",
            "CentralBrainGateway.GetBindingReadiness -> /bindings/readiness",
            "CentralBrainGateway.GetDeliveryReadiness -> /delivery/readiness",
            "CentralBrainGateway.GetPrototypeReadiness -> /prototype/readiness",
            "CentralBrainGateway.GetHardwareInterfaces -> /hardware/interfaces",
            "CentralBrainGateway.GetHardwareInterfaceActivationChecklist -> /hardware/interfaces/activation-checklist",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionStatus -> /hardware/interfaces/owner-decision-status",
            "CentralBrainGateway.SubmitHardwareInterfaceOwnerDecisionEvidence -> /hardware/interfaces/owner-decision-evidence",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceStatus -> /hardware/interfaces/owner-decision-evidence/status",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceRetentionChecklist -> /hardware/interfaces/owner-decision-evidence/retention-checklist",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceReplacementTriggerChecklist -> /hardware/interfaces/owner-decision-evidence/replacement-trigger-checklist",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceSelectedAdapterReadinessChecklist -> /hardware/interfaces/owner-decision-evidence/selected-adapter-readiness-checklist",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadBlockerRollup -> /hardware/interfaces/owner-decision-evidence/adapter-load-blocker-rollup",
            "CentralBrainGateway.DryRunHardwareInterfaceOwnerDecisionEvidenceAdapterLoad -> /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadDryRunStatus -> /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/status",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadDryRunAuditConsistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/audit-consistency",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityChecklist -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityStatus -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/status",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityAuditConsistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/audit-consistency",
            "CentralBrainGateway.DryRunHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecision -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionDryRunStatus -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/status",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionDryRunAuditConsistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/audit-consistency",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionClosureBlockerMatrix -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionReviewerMatrix -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffChecklist -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceStatus -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceAuditConsistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/audit-consistency",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceDecisionRollup -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessChecklist -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessAuditConsistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessDecisionRollup -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessDecisionReviewerAssignmentChecklist -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessDecisionReviewerAssignmentAuditConsistency -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessDecisionReviewerAssignmentAuditDecisionRollup -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency/decision-rollup",
            "CentralBrainGateway.GetHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessDecisionReviewerAssignmentAuditDecisionRollupClosureHandoffReadinessSummary -> /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency/decision-rollup/closure-handoff-readiness-summary",
            "CentralBrainGateway.GetVehicleSignals -> /vehicle/signals",
            "CentralBrainGateway.GetVehicleSignalActivation -> /vehicle/signals/activation",
            "CentralBrainGateway.GetVehicleSignalValidation -> /vehicle/signals/validation",
        ],
        "artifacts": [
            "central-brain/bindings/linux/proto/central_brain_gateway.proto",
            "central-brain/bindings/linux/ipc/central_brain_governance_client.py",
            "central-brain/bindings/linux/grpc/central_brain_grpc_server.py",
            "central-brain/bindings/linux/grpc/central_brain_grpc_client.py",
            "central-brain/deploy/linux/systemd/central-brain-linux-grpc.service",
        ],
        "req_ids": ["XSC-001", "XSC-002", "XSC-003", "XSC-004", "XSC-005", "XSC-006", "APP-004", "FW-U-003", "FW-U-004", "FW-U-006", "FW-U-008", "FW-S-004", "HW-002", "KH-001", "KH-002", "KH-003", "KH-006", "KH-007", "DEL-005", "NV-F-003", "NV-F-004", "NV-F-005", "NV-G-002", "NV-G-003", "NV-G-004", "NV-G-005", "NV-G-006", "NV-G-007", "NV-P-001", "NV-P-003", "NV-P-006", "DEL-002"],
    },
    {
        "name": "mqtt",
        "status": "planned-policy-gated",
        "platforms": ["Android", "Linux"],
        "semantic_paths": ["cloud/vehicle message topics via Policy and Privacy checks"],
        "artifacts": [],
        "req_ids": ["XSC-006", "NV-P-004"],
    },
    {
        "name": "someip",
        "status": "planned-after-vehicle-network",
        "platforms": ["Linux", "QNX/RT domain integration assumption"],
        "semantic_paths": ["vehicle cross-ECU services via service discovery"],
        "artifacts": [],
        "req_ids": ["XSC-006", "NV-P-001"],
    },
    {
        "name": "dds",
        "status": "planned-for-high-rate-topics",
        "platforms": ["Linux", "Android native"],
        "semantic_paths": [
            "planned DDS delivery for /uib/events/topics, /uib/events/recent, and /uib/events/subscriptions high-rate topics after request/cancel lifecycle commands, activation checklist, callback/watch shape, and cursor/replay storage leave contract-only mode",
        ],
        "artifacts": [],
        "req_ids": ["XSC-006", "NV-P-006"],
    },
]


class ProtocolBindingRegistry:
    """In-process binding registry for prototype discovery and smoke tests."""

    def list_payload(self) -> dict[str, Any]:
        return {
            "bindings": copy.deepcopy(BINDING_REGISTRY),
            "req_ids": BINDING_REQ_IDS,
        }

    def detail_payload(self) -> dict[str, Any]:
        bindings = copy.deepcopy(BINDING_REGISTRY)
        return {
            "bindings": bindings,
            "active_semantic_entrypoints": sorted(
                {
                    path
                    for binding in bindings
                    for path in binding.get("semantic_paths", [])
                    if path.startswith("/")
                }
            ),
            "contract_artifacts": sorted(
                {
                    artifact
                    for binding in bindings
                    for artifact in binding.get("artifacts", [])
                }
            ),
            "constraints": [
                "Protocol Binding cannot bypass Uni Info Bus semantic objects.",
                "SOA calls remain policy, lifecycle, and audit checked.",
                "Runtime & Governance precheck can be called without service dispatch; default QoS behavior is diagnostic peek, not reservation.",
                "Android Binder service sample maps Binder calls to the semantic gateway; REST remains the upstream prototype binding.",
                "Android system/privileged service integration is documented only; target signing, SELinux, and service manager choices remain platform decisions.",
                "Linux IPC active sample can use a shared Linux governance daemon for SOA precheck before forwarding allowed service invocations to the semantic gateway; it falls back to local precheck when that socket is unavailable.",
                "Linux IPC and gRPC/RPC samples call the shared governance socket through one reusable client helper for precheck plus read-only runtime/audit diagnostics, so transport replacement does not duplicate the Runtime & Governance envelope.",
                "The shared governance backend target contract is exposed at /governance/backend-contract for Android Binder, Linux IPC, and gRPC/RPC integration alignment.",
                "The governance migration check is exposed at /governance/migration-check to verify production backend replacement invariants without implementing the production backend.",
                "The governance deployment plan is exposed at /governance/deployment-plan to keep Android system service, Linux daemon, and gRPC/RPC deployment-shape decisions visible without implementing the production backend.",
                "The Android/Linux delivery readiness contract is exposed at /delivery/readiness to consolidate sample artifacts, validation commands, blockers, and non-goal boundaries for cockpit-domain engineers.",
                "The Python prototype readiness contract is exposed at /prototype/readiness to consolidate product, architecture, binding, Driver/HAL, hardware, deviation, and issue status without dispatching services.",
                "The vehicle signal catalog is exposed at /vehicle/signals as a VSS-style read-only Vehicle Signal Adapter contract; it does not load DBC/ARXML, open VHAL, connect SocketCAN, or dispatch Driver/HAL.",
                "The vehicle signal read-bridge activation criteria are exposed at /vehicle/signals/activation for DBC/ARXML, Android VHAL/vendor AIDL, Linux SocketCAN, and vendor gateway review; it does not activate any real bridge or add Driver/HAL code.",
                "The vehicle signal read-bridge validation envelope is exposed at /vehicle/signals/validation to collect schema-source metadata, adapter ownership, Android/Linux parity, and DRV-GAP-002 evidence before any bridge can be activated; it does not parse schemas or access hardware.",
                "The Event subscription contract is exposed at /uib/events/subscriptions plus request/cancel lifecycle command endpoints, /uib/events/subscriptions/transport-readiness, /uib/events/subscriptions/decision-matrix, /uib/events/subscriptions/activation-checklist, /uib/events/subscriptions/callback-watch-shape, /uib/events/subscriptions/cursor-replay-storage, /uib/events/subscriptions/backpressure-qos-evidence, /uib/events/subscriptions/readiness-rollup, POST /uib/events/subscriptions/activation-evidence, GET /uib/events/subscriptions/activation-evidence/status, GET /uib/events/subscriptions/activation-evidence/retention-checklist, GET /uib/events/subscriptions/activation-evidence/decision-status-rollup, GET /uib/events/subscriptions/activation-evidence/approval-dry-run/status, GET /uib/events/subscriptions/activation-evidence/approval-authority-checklist, GET /uib/events/subscriptions/activation-evidence/approval-authority-checklist/audit-consistency, GET /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-blocker-rollup, POST /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run, GET /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/status, GET /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/audit-consistency, GET /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix, GET /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist, and GET /uib/events/subscriptions/activation-evidence/approval-authority-checklist/decision-dry-run/closure-blocker-matrix/owner-handoff-checklist/audit-consistency to fix lifecycle, cursor, replay storage, backpressure/QoS evidence, callback/watch readiness, owner decisions, activation evidence gates, activation evidence intake/status/retention/decision rollup shape, activation approval dry-run status shape, activation approval authority checklist shape, approval authority audit consistency, approval decision blocker rollup, approval decision dry-run request/status/audit shape, approval decision closure blocker matrix, approval decision owner handoff checklist and audit consistency, callback/watch API shape, end-to-end readiness blockers, governance, and Android/Linux binding parity without approval/evidence/result/handoff persistence, owner assignment, evidence attachment, review queue update, retention store creation, delete/export workflow, gate closure, transport selection, persistence, QoS activation, callback/watch registration, broker startup, SSE/WebSocket, DDS runtime, or high-rate data plane.",
                "Linux shared governance daemon also exposes runtime status and recent audit diagnostics over the same Unix socket; IPC/gRPC use that direct path before REST fallback and these operations do not dispatch services.",
                "Linux gRPC/RPC sample mirrors the proto GatewayRequest/GatewayResponse fields over a dependency-free JSON TCP wrapper because grpcio is not available in this workspace.",
                "Linux gRPC/RPC InvokeService uses the same shared governance daemon precheck with local fallback before forwarding allowed SOA calls.",
                "Virtualization and driver layers are documented integration assumptions only in this increment.",
                "The hardware empty-interface catalog is exposed at /hardware/interfaces, /hardware/interfaces/activation-checklist, /hardware/interfaces/owner-decision-status, POST /hardware/interfaces/owner-decision-evidence, GET /hardware/interfaces/owner-decision-evidence/status, GET /hardware/interfaces/owner-decision-evidence/retention-checklist, GET /hardware/interfaces/owner-decision-evidence/replacement-trigger-checklist, GET /hardware/interfaces/owner-decision-evidence/selected-adapter-readiness-checklist, GET /hardware/interfaces/owner-decision-evidence/adapter-load-blocker-rollup, POST /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run, GET /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/status, GET /hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/audit-consistency, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/status, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/audit-consistency, POST /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/status, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/audit-consistency, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/audit-consistency, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist, GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency, and GET /hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency/decision-rollup/reviewer-assignment-checklist/audit-consistency/decision-rollup for Android and Linux bindings; it records owner, ABI, Driver/HAL gap, safety policy, smoke-test, rollback decision gates, no-store evidence reference intake, no-store owner evidence review status, retention/closure checklist decisions, empty-interface replacement trigger gates, selected-adapter readiness evidence, adapter-load blockers, adapter-load approval dry-run rejection, no-store dry-run status, dry-run audit consistency, approval-authority decisions, approval-authority no-store status, approval-authority audit consistency, approval decision dry-run rejection, approval decision dry-run no-store status, approval decision dry-run audit consistency, approval closure/reviewer/evidence handoff blockers, handoff acceptance status, acceptance audit consistency, acceptance decision rollup, closure readiness checklist, closure readiness audit consistency, closure readiness decision rollup, closure decision reviewer assignment checklist, reviewer assignment audit consistency, and reviewer assignment audit decision rollup without opening devices, calling HALs, allocating shared memory, reading evidence stores, updating review queues, creating delete/export workflows, persisting approvals, accepting packets, selecting/loading/replacing adapters, closing gates, triggering Driver/HAL development, or performing virtualization work.",
            ],
            "req_ids": BINDING_REQ_IDS + ["XSC-004", "HW-002", "KH-001", "KH-002", "KH-003", "KH-006", "KH-007", "DEL-001", "DEL-002", "DEL-003", "DEL-004", "DEL-005", "NV-F-003", "NV-F-004", "NV-F-005"],
        }

    def readiness_payload(self) -> dict[str, Any]:
        rows = copy.deepcopy(BINDING_READINESS_ROWS)
        return {
            "readiness": rows,
            "summary": {
                "production_ready": False,
                "active_samples": [
                    row["binding"]
                    for row in rows
                    if row["current_state"] in {"active-prototype", "active-sample", "grpc-json-active-sample", "service-stub-sample"}
                ],
                "planned_bindings": [
                    row["binding"]
                    for row in rows
                    if row["current_state"].startswith("planned")
                ],
                "driver_development_triggered": False,
                "virtualization_development_triggered": False,
                "service_dispatch_triggered": False,
            },
            "non_goals": [
                "No production shared governance backend is implemented by this readiness contract.",
                "No true gRPC runtime, MQTT broker, SOME/IP stack, DDS broker, Driver/HAL, Safety Runtime, vehicle bus, hardware access, or virtualization code is added.",
            ],
            "next_decisions": [
                "Choose target Linux distro/package format before replacing the package profile sample.",
                "Choose true gRPC runtime and credential source before replacing the JSON TCP wrapper.",
                "Choose Android system/privileged service owner, signing, and SELinux shape before framework integration.",
            ],
            "req_ids": sorted(set(BINDING_REQ_IDS + ["XSC-005", "DEL-001", "DEL-002", "DEL-003", "DEL-004"])),
        }
