#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

DOC="$ROOT_DIR/docs/CENTRAL_BRAIN_ANDROID_SYSTEM_SERVICE_INTEGRATION.md"
ANDROID_README="$ROOT_DIR/central-brain/bindings/android/README.md"
PLATFORM_DELTA="$ROOT_DIR/docs/CENTRAL_BRAIN_PLATFORM_DELTA.md"
DELIVERY_TARGETS="$ROOT_DIR/docs/CENTRAL_BRAIN_DELIVERY_TARGETS.md"
DRIVER_SUPPORT="$ROOT_DIR/docs/CENTRAL_BRAIN_DRIVER_INTERFACE_SUPPORT.md"
DEVIATIONS="$ROOT_DIR/docs/CENTRAL_BRAIN_ARCHITECTURE_DEVIATIONS.md"
ISSUES="$ROOT_DIR/docs/CENTRAL_BRAIN_ARCHITECTURE_ISSUES.md"
MANIFEST="$ROOT_DIR/central-brain/android-console/AndroidManifest.xml"

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "missing required Android system service file: $path" >&2
    exit 1
  fi
}

require_text() {
  local path="$1"
  local pattern="$2"
  if ! grep -Fq "$pattern" "$path"; then
    echo "missing pattern '$pattern' in $path" >&2
    exit 1
  fi
}

require_file "$DOC"
require_file "$ANDROID_README"
require_file "$PLATFORM_DELTA"
require_file "$DELIVERY_TARGETS"
require_file "$DRIVER_SUPPORT"
require_file "$DEVIATIONS"
require_file "$ISSUES"
require_file "$MANIFEST"

for req_id in DEL-001 DEL-003 DEL-004 DEL-005 XSC-001 APP-004 XSC-002 XSC-003 XSC-004 XSC-005 XSC-006 HW-002 NV-P-002 NV-P-005 FW-U-007 FW-S-005 NV-G-005 KH-003 KH-006 KH-007; do
  require_text "$DOC" "$req_id"
done

require_text "$DOC" "system/privileged service"
require_text "$DOC" "Privileged app service"
require_text "$DOC" "Framework system service"
require_text "$DOC" "Vendor native gateway bridge"
require_text "$DOC" "BIND_CENTRAL_BRAIN_GATEWAY"
require_text "$DOC" "planAgentTaskJson"
require_text "$DOC" "executeAgentTaskJson"
require_text "$DOC" "invokeSkillJson"
require_text "$DOC" "queryMemoryJson"
require_text "$DOC" "getEventSubscriptionTransportReadinessJson"
require_text "$DOC" "getEventSubscriptionDecisionMatrixJson"
require_text "$DOC" "getEventSubscriptionActivationChecklistJson"
require_text "$DOC" "getEventSubscriptionCallbackWatchShapeJson"
require_text "$DOC" "getEventSubscriptionCursorReplayStorageJson"
require_text "$DOC" "getEventSubscriptionBackpressureQosEvidenceJson"
require_text "$DOC" "getEventSubscriptionReadinessRollupJson"
require_text "$DOC" "submitEventSubscriptionActivationEvidenceJson"
require_text "$DOC" "getEventSubscriptionActivationEvidenceStatusJson"
require_text "$DOC" "getEventSubscriptionActivationEvidenceRetentionChecklistJson"
require_text "$DOC" "getEventSubscriptionActivationEvidenceDecisionStatusRollupJson"
require_text "$DOC" "/uib/events/subscriptions/activation-evidence/decision-status-rollup"
require_text "$DOC" "readiness rollup"
require_text "$DOC" "activation evidence"
require_text "$DOC" "review status"
require_text "$DOC" "retention checklist"
require_text "$DOC" "decision status rollup"
require_text "$DOC" "precheckGovernanceJson"
require_text "$DOC" "getGovernanceBackendContractJson"
require_text "$DOC" "getGovernanceMigrationCheckJson"
require_text "$DOC" "getBindingReadinessJson"
require_text "$DOC" "getDeliveryReadinessJson"
require_text "$DOC" "getDriverHalGapsJson"
require_text "$DOC" "getHardwareInterfacesJson"
require_text "$DOC" "getHardwareInterfaceActivationChecklistJson"
require_text "$DOC" "dryRunHardwareInterfaceOwnerDecisionEvidenceAdapterLoadJson"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadDryRunStatusJson"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadDryRunAuditConsistencyJson"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityChecklistJson"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityStatusJson"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalAuthorityAuditConsistencyJson"
require_text "$DOC" "dryRunHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionJson"
require_text "$DOC" "HW ApDec"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionClosureBlockerMatrixJson"
require_text "$DOC" "HW ApBlock"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionReviewerMatrixJson"
require_text "$DOC" "HW ApRev"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffChecklistJson"
require_text "$DOC" "HW ApHand"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceStatusJson"
require_text "$DOC" "HW ApHStat"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceAuditConsistencyJson"
require_text "$DOC" "HW ApHAud"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceDecisionRollupJson"
require_text "$DOC" "HW ApHRoll"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessChecklistJson"
require_text "$DOC" "HW ApHClose"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalReviewerEvidenceHandoffAcceptanceClosureReadinessAuditConsistencyJson"
require_text "$DOC" "HW ApHCAud"
require_text "$DOC" "/governance/precheck"
require_text "$DOC" "shared Runtime & Governance backend target contract"
require_text "$DOC" "migration readiness"
require_text "$DOC" "/native/driver-gaps"
require_text "$DOC" "/hardware/interfaces"
require_text "$DOC" "/hardware/interfaces/activation-checklist"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-dry-run"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/audit-consistency"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/status"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-dry-run/audit-consistency"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/status"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/status"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/audit-consistency"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/decision-rollup/closure-readiness-checklist/audit-consistency"
require_text "$DOC" "/hardware/interfaces/owner-decision-evidence/adapter-load-approval-authority-checklist/decision-dry-run/closure-blocker-matrix/reviewer-matrix/evidence-handoff-checklist/acceptance-status/audit-consistency"
require_text "$DOC" "getHardwareInterfaceOwnerDecisionEvidenceAdapterLoadApprovalDecisionDryRunStatusJson"
require_text "$DOC" "com.centralbrain.permission.BIND_GATEWAY"
require_text "$DOC" "Binder UID"
require_text "$DOC" "SELinux"
require_text "$DOC" "Policy 仍由 Runtime & Governance 执行"
require_text "$DOC" "不新增 Android framework patch"
require_text "$DOC" "Driver/HAL"
require_text "$DOC" "ISSUE-013"

require_text "$ANDROID_README" "CENTRAL_BRAIN_ANDROID_SYSTEM_SERVICE_INTEGRATION.md"
require_text "$PLATFORM_DELTA" "CENTRAL_BRAIN_ANDROID_SYSTEM_SERVICE_INTEGRATION.md"
require_text "$DELIVERY_TARGETS" "CENTRAL_BRAIN_ANDROID_SYSTEM_SERVICE_INTEGRATION.md"
require_text "$DRIVER_SUPPORT" "Android system/privileged service"
require_text "$DEVIATIONS" "CENTRAL_BRAIN_ANDROID_SYSTEM_SERVICE_INTEGRATION.md"
require_text "$ISSUES" "ISSUE-013"
require_text "$MANIFEST" "BIND_CENTRAL_BRAIN_GATEWAY"

echo "Central Brain Android system service docs check passed"
